# Runs by interactive zsh sessions only.

# ==== Define the shell prompt ====

parse_git_branch() {
    git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/[\1]/p'
}

# Store exit status of the command to avoid clobbering $?
precmd() {
    # store the exit status of the command
    LAST_CMD_EXIT_STATUS=$?

    # Get the git branch and store it
    GIT_BRANCH=$(parse_git_branch)
}

# Using 'precmd' or PROMPT_SUBST is better for dynamic prompt updates
colored_dollar() {
    if [ "$LAST_CMD_EXIT_STATUS" -eq 0 ]; then
        echo "%F{green}"
    else
        echo "%F{red}"
    fi
}

# Enable prompt substitution to allow command/function evaluation
setopt PROMPT_SUBST

PROMPT='[%F{white}%n@%m]%L:%F{blue}%1~%f/${GIT_BRANCH}$(colored_dollar)%#%f '
RPROMPT='%*'

# ==== PATH ====
export PATH="$PATH:$HOME/scripts"

# ==== aliases ====
# 用 `-F` 在目錄名右邊顯示 `/`
alias ls='eza -F'

# colorful man using `bat`
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"

# to get the exit status of `jq` command
alias jq='jq -e'

# make the 'null' of `jq` command readable
export JQ_COLORS="1;90:1;34:0;34:1;36:0;33:1;37:1;37"       # from "https://www.azurecitadel.com/terraform/environments/macos/"

alias watch='hwatch --color'

# ==== completions ====

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath+=~/.docker/completions
autoload -Uz compinit && compinit
# End of Docker CLI completions

# Add poetry completion by following "https://python-poetry.org/docs/"
fpath+=~/.zfuncs/
autoload -Uz compinit && compinit
# End of poetry completion

source <(kubectl completion zsh)
